name: 'Trigger-Binder-build'
on:
  push:
    branches:
      - develop 

jobs:
  trigger-binder-build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1.1.0
        with:
          target-repo: osscar-org/quantum-mechanics  
          service-name: gh 
          target-state: develop 
